#pragma once
#define _USE_MATH_DEFINES
#include <gl/glew.h>
#include <GLFW/glfw3.h>
#include <chrono>
#include <cmath>
#include <glm/ext/matrix_clip_space.hpp>
#include <glm/ext/matrix_transform.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/ext.hpp>
#include <iostream>
#include <stdexcept>